### ISSUE TITLE
cloud-run-cloud-sql 500 internal server error

### ISSUE THREAD

**Issue by bsweet2** [GoogleCloudPlatform/serverless-expeditions#3]
I'm getting a 500 Internal Server Error after I execute ./build-and-deploy.sh and click on the link.

sqlalchemy.exc.ProgrammingError: (pg8000.exceptions.ProgrammingError) {'S': 'FATAL', 'V': 'FATAL', 'C': '3D000', 'M': 'database "postgre-db" does not exist', 'F': 'postinit.c', 'L': '890', 'R': 'InitPostgres'}"

**Comment by glasnt** [comment]
Hi! Thanks for reaching out. 

I was going to suggest that you should check both the Cloud Build and Cloud Run logs to see what the internal error message is, but you just did!

The error you have there is `database \"postgre-db\" does not exist`, which is correct, as the `./build-and-deploy.sh` doesn't include the databaset setup steps.

**Comment by bsweet2** [comment]
Thanks Katie!

I realize now that I was using the instance name (postgre-db) instead of the db name (postgres) in my .env file.
